apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 121027/express-fe
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "3000"
          - name: BASE_URL
            value: http://backend:8080/api
